### PR TITLE
Initial poster draft

### PR DESCRIPTION
**Pull request by richarel**
Here's the first attempt of the expo poster. Check it out and critique it so we can have the best poster at the expo!

### CODE REVIEW

**Review by shellajt — CHANGES_REQUESTED** [review]
Good Work! Thats really good. I'd add the raw file you used to make the pdf to git, just in case something happens or we need to edit.

I think we should add Encryption to the feature list in the upper right. Encryption is impressive and could help set us apart. We could add the Google Http Client and Jackson to the Developed Using box. I'd also specify that we use Model View Controller (MVC) in the architecture segment

**Review by shellajt — CHANGES_REQUESTED** [review]
Model View Controller is the name of the architecture, not the controller segment

**Review by shellajt — APPROVED** [review]

**Review by taylerhow — APPROVED** [review]
Looks awesome!

**Review by cjm721 — APPROVED** [review]

**Review by cjm721 — CHANGES_REQUESTED** [review]
Put a border on the images so can see the end of the application.

**Review by cjm721 — APPROVED** [review]
The lines are there. Seems to just be a PDF visual bug as when you zoom in they appear.

**Pull request merged**
